# Goal of this project

The goal of this project is to decompose one matrix into two L and U matrices using Doolittle and Crout's decomposition algorithms, in order to solve a system of linear equations.

The system of linear equations we are trying to solve is:

2x + 3y - 1 = 2 <br/>
4x + 4y - 1 = -1<br/>
-2x -3y + 4z = 1

# Importing the libraries needed for the project

In [113]:
import numpy as np 

For this project, the only library we need is numpy for manipulating arrays.

### Next step: defining the functions for the project

After this, we are going to define the main functions needed for the LU decomposition using Doolittle and Crout's methods.

We will have four main functions: one for forward substitution, one for backward substitution, one for Doolittle's algorithm and one for Crout's algorithm. On top of this, we will also have an auxiliary function to compute the final results of each algorithm.

# Function for the forward substitution

In [114]:
def forward_substitution(L, b):

    y = np.full_like(b,0) # Creating the y vector the same size as the b vector
    
    for k in range(len(b)):
        
        y[k] = b[k]
        
        for i in range(k):
            
            y[k] = y[k] - (L[k, i]*y[i])
            
        y[k] = y[k] / L[k, k] # Using forward substitution to find the value of y
    
    # Returning the y vector
    
    return y

This functions takes as input a lower triangular matrix L and a right-side vector b. It returns the solution vector y using the equation Ly = b.







# Function for the backwards substitution

In [115]:
def backward_substitution(U, y):
    
    x = np.full_like(y,0) # Creating the x vector the same size as the y vector
    
    for k in range(len(x), 0, -1):
        
      x[k-1] = (y[k-1] - np.dot(U[k-1, k:], x[k:])) / U[k-1, k-1] # Using backward substitution to find the value of x
     
    # Returning the solution vector x
    
    return x

This functions takes as input a lower triangular matrix U and a right-side vector y. It returns the solution vector x using the equation Ux = y.

# Function for Doolittle's algorithm

In [116]:
def doolittle(A):
    
  # Creating two L and U matrices filled with 0s and the same size as A

  L = np.matrix([[0,0,0],[0,0,0],[0,0,0]])
  U = np.matrix([[0,0,0],[0,0,0],[0,0,0]])
  n = len(A)
  
  # for-loop in order to set the j,j-th entry of U to 1
    
  for z in range(n):
        
    L[z, z] = 1
    
    U[z, z] = (A[z, z] - np.dot(L[z, :z], U[:z, z]))
    
    for i in range(z+1, n):
        
      U[z, i] = (A[z, i] - np.dot(L[z, :z], U[:z, i]))
    
    for k in range(z+1, n):
        
      L[k, z] = (A[k, z] - np.dot(L[k, :z], U[:z, z])) / U[z, z]

  # Returning the matrices L and U i.e. the A matrix decomposed using Doolittle's algorithm

  return (L, U)

This function decomposes the matrix A into the two L and U matrices using Doolittle's algorithm.

# Function for Crout's algorithm

In [117]:
def crout(A):
        
    # Creating two L and U matrices filled with 0s and the same size as A

    L = np.matrix([[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0]])
    U = np.matrix([[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0]])
    n = len(A)
    
    # for-loop in order to set the j,j-th entry of U to 1
    
    for z in range(n):
        
        U[z,z] = 1             
        
        # for-loop starting at L[j][j] in order to solve the j-th column of L
        
        for j in range(z,n):

            # Declaring a temporary L to store values and insert them later in the L matrix

            temporary_L = float(A[j,z])
            
            for k in range(z):
                
                temporary_L -= L[j,k]*U[k,z]
                
            L[j,z] = temporary_L
            
        # for-loop starting at U[j][j+1] in order to solve the j-th row of U
        
        for j in range(z+1, n):
            
            # Declaring a temporary U to store values and insert them later in the U matrix
            
            temporary_U = float(A[z,j])
            
            for k in range(z):
                
                temporary_U -= L[z,k]*U[k,j]
                
            U[z,j] = temporary_U / L[z,z]
    
    # Returning the matrices L and U i.e. the A matrix decomposed using Crout's algorithm
    
    return (L, U)

This function decomposes the matrix A into the two L and U matrices using Crout's algorithm.

# Function for computing the final solution

In [118]:
def computing_final_solution(A, b, algorithm_used):
    
    # Creating the L and U matrices using the specified algorithm
    
    L, U = algorithm_used(A)
    
    print("L = " + str(L) + "\n")
    print("U = " + str(U) + "\n")
    
    # Calling forward then backward substitution
    
    y = forward_substitution(L,b)
    x = backward_substitution(U,y)
    
    # Returning the solution vector x
    
    return x

This function decomposes the A matrix into L and U matrices by calling the specified algorithm (i.e. Doolittle or Crout). After this, it uses forward then backward substitution to find the x vector (i.e. the solution for the linear system of equations).

# Declaring the matrices to solve the system of linear equations

In [119]:
# Declaring the A and b matrices for the final solution

A = np.matrix([[2.0,3.0,-1.0],[4.0,4.0,-1.0],[-2.0,-3.0,4.0]])

b = np.array([2.0,-1.0,1.0])

# Printing out the final solution

In [120]:
# Printing out the results

# For Doolittle 

print("The solution using Doolittle's algorithm:" + "\n")
print( "x = " + str(computing_final_solution(A,b, doolittle)) + "\n" )

# For Crout 

print("\n" + "The solution using Crout's algorithm:" + "\n")
print( "x = " + str(computing_final_solution(A,b, crout)) + "\n")

The solution using Doolittle's algorithm:

L = [[ 1  0  0]
 [ 2  1  0]
 [-1  0  1]]

U = [[ 2  3 -1]
 [ 0 -2  1]
 [ 0  0  3]]

x = [-3.  3.  1.]


The solution using Crout's algorithm:

L = [[ 2.  0.  0.]
 [ 4. -2.  0.]
 [-2.  0.  3.]]

U = [[ 1.   1.5 -0.5]
 [ 0.   1.  -0.5]
 [ 0.   0.   1. ]]

x = [-3.  3.  1.]



# Final result

Therefore, the final solution for both Doolittle and Crout algorithms is x = -3, y = 3 and z = 1. This means that those values of x, y and z can solve the system of linear equations.